title: Hu YongTao's Homepage
page-top-title: Hu YongTao
top-section-bg-text: Marine Engineering
home-subtitle: Hu YongTao&ensp;|&ensp;胡永涛
copyright-text: '&copy; Hu YongTao 2023-2024. All Rights Reserved.'
